package com.google.android.gms.common.api.internal;

import android.support.annotation.NonNull;
import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult.zza;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.TransformedResult;
import java.util.concurrent.TimeUnit;

public final class zzcr<R extends Result> extends OptionalPendingResult<R> {
    private final zzs<R> zzfru;

    public zzcr(PendingResult<R> pendingResult) {
        if (pendingResult instanceof zzs) {
            this.zzfru = (zzs) pendingResult;
            return;
        }
        throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
    }

    public final R await() {
        return this.zzfru.await();
    }

    public final R await(long j, TimeUnit timeUnit) {
        return this.zzfru.await(j, timeUnit);
    }

    public final void cancel() {
        this.zzfru.cancel();
    }

    public final R get() {
        if (isDone()) {
            return await(0, TimeUnit.MILLISECONDS);
        }
        throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
    }

    public final boolean isCanceled() {
        return this.zzfru.isCanceled();
    }

    public final boolean isDone() {
        return this.zzfru.isReady();
    }

    public final void setResultCallback(ResultCallback<? super R> resultCallback) {
        this.zzfru.setResultCallback(resultCallback);
    }

    public final void setResultCallback(ResultCallback<? super R> resultCallback, long j, TimeUnit timeUnit) {
        this.zzfru.setResultCallback(resultCallback, j, timeUnit);
    }

    @NonNull
    public final <S extends Result> TransformedResult<S> then(@NonNull ResultTransform<? super R, ? extends S> resultTransform) {
        return this.zzfru.then(resultTransform);
    }

    public final void zza(zza com_google_android_gms_common_api_PendingResult_zza) {
        this.zzfru.zza(com_google_android_gms_common_api_PendingResult_zza);
    }

    public final Integer zzagi() {
        return this.zzfru.zzagi();
    }
}
