package com.lifesense.ble.p003a;

public enum af {
    WORKING_FREE,
    WORKING_DEVICE_PAIRING_FOR_A2,
    WORKING_DATA_UPLOADING_FOR_A2,
    WORKING_DEVICE_PAIRING_FOR_A3,
    WORKING_DATA_UPLOADING_FOR_A3,
    WORKING_DATA_UPLOADING_FOR_GENERIC_FAT,
    WORKING_DATA_UPLOADING_FOR_GLUCOSE_METER,
    WORKING_DEVICE_PAIRING_FOR_A4
}
